name: 'Install'
description: 'Sets up Node, and installs dependencies'
inputs:
  monorepo:
    default: 'false'
    required: false
  npm_token:
    description: 'NPM token for private packages'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set NPM token
      if: ${{ inputs.npm_token != '' }}
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" > ~/.npmrc

    - name: Install pnpm
      shell: bash
      run: |
        npm install -g pnpm

    - name: Install dependencies (monorepo)
      if: ${{ format('{0}', inputs.monorepo) == 'true' }}
      shell: bash
      run: |
        pnpm install
        pnpm exec turbo run setup

    - name: Install dependencies
      if: ${{ format('{0}', inputs.monorepo) != 'true' }}
      shell: bash
      run: |
        pnpm install --frozen-lockfile --prod=false
