name: 'Lint Code'
description: 'Runs Commitlint, ESLint, and Prettier to ensure code quality.'

inputs:
  monorepo:
    default: 'false'
    description: "Set mode to 'monorepo' or 'single'."
    required: false

runs:
  using: 'composite'
  steps:
    - name: Commitlint
      shell: bash
      run: |
        git log -1 --pretty=%B | pnpm exec commitlint

    - name: ESLint
      shell: bash
      run: |
        if [ "${{ inputs.monorepo }}" = "true" ]; then
          echo "Running in monorepo mode."
          pnpm exec turbo run lint
        else
          echo "Running in single repository mode."
           pnpm eslint . --max-warnings=0
        fi

    - name: Prettier
      shell: bash
      run: |
        if [ "${{ inputs.monorepo }}" = "true" ]; then
          echo "Running in monorepo mode."
          pnpm exec turbo run prettier:check
        else
          echo "Running in single repository mode."
           pnpm prettier --check .
        fi
