name: CI/CD Main Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: kurocado-studio/platform/.github/workflows/workflow.lint-format.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync:
    needs: lint
    uses: kurocado-studio/platform/.github/workflows/workflow.sync.yml@main
    with:
      branch_name: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT_FORCE_PUSH: ${{ secrets.PAT_FORCE_PUSH }}
